;;; magit-org-todos-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from magit-org-todos.el

(autoload 'magit-org-todos-insert-org-todos "magit-org-todos" "\
Insert org todos from the local todo.org.")
(autoload 'magit-org-todos-autoinsert "magit-org-todos" "\
Automatically insert todo section into magit status buffer.")
(register-definition-prefixes "magit-org-todos" '("magit-org-todos-"))

;;; End of scraped data

(provide 'magit-org-todos-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; magit-org-todos-autoloads.el ends here
