;;; org-rich-yank-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-rich-yank.el

(autoload 'org-rich-yank-enable "org-rich-yank" "\
Add the advices that store the buffer of the current kill.")
(autoload 'org-rich-yank "org-rich-yank" "\
Yank, surrounded by #+BEGIN_SRC block with major mode of originating buffer." t)
(register-definition-prefixes "org-rich-yank" '("org-rich-yank-"))

;;; End of scraped data

(provide 'org-rich-yank-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-rich-yank-autoloads.el ends here
